### ISSUE TITLE
Show all point values

### ISSUE THREAD

**Issue by skotturi** [alangrafu/radar-chart-d3#28]
Thanks for this awesome lib, 
I'd like to show all the point values by default instead of only showing them when hovering. 
I've been searching through the code and looked online for suggestions but cannot find anything.

Can you just point me towards the location of where this would be modified for my use? 

Thanks in advance!

**Comment by alangrafu** [comment]
Take a look at https://github.com/alangrafu/radar-chart-d3/blob/master/src/radar-chart.js#L247
